import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>hi</div>
      <button onClick={() => signIn()}>Login</button>

      {session && (
        <div>
          <div>Logged in as {session.user.email}</div>
          <div>Session expires at {session.expires}</div>
        </div>
      )}
    </>
  );
};

export default Home;
